service: hosting-amazon-lambda

provider:
  name: aws
  runtime: provided
  region: us-west-2

package:
  individually: true
  artifact: bin/Release/netcoreapp3.1/Hosting.Amazon.Lambda.Sample.zip
  
functions:
  sample:
    handler: Hosting.Amazon.Lambda::Hosting.Amazon.Lambda.Program::Main
    events:
      - http:
          path: /
          method: ANY