name: publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Pack
      run: dotnet pack ./src/Hosting.Amazon.Lambda/ -c Release
    - name: Publish
      run: dotnet nuget push **/*.nupkg -k $NUGET_API_KEY -s $NUGET_SOURCE -n true
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        NUGET_SOURCE: https://api.nuget.org/v3/index.json
    
